### ISSUE TITLE
Org-roam will not launch  

### ISSUE THREAD

**Issue by shrysr** [apoptosis/episteme#11]
I have the following trace running org-roam-node-find. This is a separate emacs instance launched using ./episteme, so I' reasonably certain it is not my config or machine. I've not been able to debug this much... My first suspicion was possible error in the node's formatting however, the random files I checked appear valid. 

```
Debugger entered--Lisp error: (error "org-roam-node-slug is already defined as something...")
  signal(error ("org-roam-node-slug is already defined as something..."))
  error("%s is already defined as something else than a gen..." org-roam-node-slug)
  cl-generic-ensure-function(org-roam-node-slug)
  cl-generic-define-method(org-roam-node-slug nil ((node org-roam-node)) nil (closure (cl-struct-org-roam-node-tags org-ref-cite-types t) (node) "Return the slug of NODE." (progn (let ((title (progn (or ... ...) (aref node 12))) (slug-trim-chars '(768 769 770 771 772 774 775 776 777 778 780 795 803 804 805 807 813 814 816 817))) (let* ((--cl-nonspacing-mark-p-- #'...)) (progn (let* (...) (progn ...))))))))
  eval-buffer(#<buffer  *load*> nil "/home/shreyas/.config/episteme/straight/build/org-..." nil t)  ; Reading at buffer position 16602
  load-with-code-conversion("/home/shreyas/.config/episteme/straight/build/org-..." "/home/shreyas/.config/episteme/straight/build/org-..." nil t)
  autoload-do-load((autoload "org-roam" "Find and open an Org-roam node by its title or ali..." t nil) org-roam-node-find)
  command-execute(org-roam-node-find)
```

**Comment by dustinlacewell** [comment]
Hmm, it's working OK here.

**Comment by Lord-Valen** [comment]
Did you verify that roam was working with `M-x org-roam-setup`? If this throws an error related to SQLite, make sure you have a C compiler installed.

Did you make any modifications to the config in `~/.config/episteme`?
Does roam work with your own instance of emacs?

**Comment by shrysr** [comment]
No - org-roam-setup would not launch for the epi setup. I believe the error was the same as before, but I will post a trace in a bit.  I have a personal org roam v1 and now v2 setup which work fine, so unlikely a compiler issue. 

No changes made to config. Vanilla epi setup.

**Comment by dustinlacewell** [comment]
I'm really not sure about this.

Can you:
- reset hard to the latest git commit and restart?
- run `straight-pull-all` then `straight-rebuild-all` to see if that works?
- if not delete `~/.config/episteme` and relaunch to see if it properly bootstraps?

**Comment by shrysr** [comment]
I've done all 3 steps progressively. Finally also re-cloned the repo in addtion to deleting the `~/.config/episteme ` folder. I do not see any error during bootstrap. Once all is done, I get the attached trace when I call up org-roam-find-node. I'm on Emacs 27.1 

[org-roam-backtrace.txt](https://github.com/apoptosis/episteme/files/6873048/org-roam-backtrace.txt)

If I call org-roam-setup after that, I get the following trace : 
[org-roam-setup-trace.txt](https://github.com/apoptosis/episteme/files/6873051/org-roam-setup-trace.txt)

**Comment by dustinlacewell** [comment]
Can you tell me what version of Org you're running with `C-h v org-version` ?

**Comment by dustinlacewell** [comment]
FWIW, I and Windows users (as per Chocolatey) would be running Emacs 27.2

**Comment by dustinlacewell** [comment]
Made stale by refactor.
