### ISSUE TITLE
Roam V2 Migration Warning Still Issued

### ISSUE THREAD

**Issue by Lord-Valen** [apoptosis/episteme#12]
Running `org-roam-setup` for the first time still issues the migration warning. The warning is not issued on subsequent attempts.

**Comment by dustinlacewell** [comment]
Probably fixed in https://github.com/apoptosis/episteme/commit/c336ce611f8b98334ad035906d44ee1955cbcca1

**Comment by dustinlacewell** [comment]
Actually fixed in https://github.com/apoptosis/episteme/commit/1e09aac03143bd871af8293bf404256bd710c343
