### ISSUE TITLE
C-<return> does not always open the highlighted item.

### ISSUE THREAD

**Issue by Lord-Valen** [apoptosis/episteme#14]
Steps to reproduce:
1. Open Episteme
2. `C-c x` `o`
3. Navigate into `episteme`
4. Use `C-<return>` on `user-guide.org`

`user-guide.org` does not open.

Workaround:
1. Navigate into `user-guide.org`
2. use `C-<return>` on one of its contents

**Comment by Lord-Valen** [comment]
It's probably an upstream issue with [helm-org-walk](https://github.com/dustinlacewell/helm-org-walk).

**Comment by dustinlacewell** [comment]
`C-<return>` will only work once you're in the file.

**Comment by dustinlacewell** [comment]
If you:
- `M-x straight-pull-package` against `helm-org-walk`
- `M-x straight-rebuild-package` against `helm-org-walk`
- Restart Episteme

Then `C-<return>` will work on non-heading items.
